# Generated by Django 3.0.2 on 2020-04-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='work_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('start_work', models.DateTimeField()),
                ('end_work', models.DateTimeField()),
                ('job_position', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
            ],
        ),
    ]
