# Generated by Django 3.0.2 on 2020-04-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('picture', models.ImageField(height_field=300, max_length=300, upload_to='useruploadedpics', width_field=300)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
