# Generated by Django 3.0.2 on 2020-05-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_checking'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(height_field=300, max_length=300, upload_to='useruploadedpics', width_field=300)),
                ('description', models.TextField()),
            ],
        ),
    ]
